"""Load the deterministic ADK agent factory generated by the runtime CLI."""

from __future__ import annotations

import importlib.util
from pathlib import Path
from types import ModuleType

from carrefour_runtime.services.process.errors import ProcessExecutionError

RUNTIME_APP_NAME = "carrefour-runtime"


def load_generated_agent(path: Path) -> ModuleType:
    """Import the generated Python factory or raise a sanitized process error."""
    if not path.is_file():
        raise ProcessExecutionError(
            "agente gerado ausente; execute generate antes de process",
            error_code="generated_agent_missing",
            component="adk_workflow_executor",
        )

    try:
        module_spec = importlib.util.spec_from_file_location(
            "carrefour_generated_agent", path
        )
        if module_spec is None or module_spec.loader is None:
            raise ImportError
        module = importlib.util.module_from_spec(module_spec)
        module_spec.loader.exec_module(module)
        return module
    except Exception as error:
        raise ProcessExecutionError(
            "não foi possível carregar o agente gerado",
            error_code="generated_agent_load_failed",
            component="adk_workflow_executor",
            error_type=type(error).__name__,
        ) from error
